name: Hub
version: '1.0-SNAPSHOT'
main: de.acGames.hub.Hub
api-version: '1.21'
commands:
  spawnset:
    description: "Set the Hub were players are teleported to."
    usage: "/spawnset"
    op-required: true
    permission: "plugin.minecraft.op"
    permission-message: "You do not have permission to use this command."

  spawn:
    description: "Teleport to the spawn location."
    usage: "/spawn"